Fix the bootstrap for the PHP functions
The bootstrap process must stay alive for ever.

diff --git a/runtime/layers/function/bootstrap b/runtime/layers/function/bootstrap
--- a/runtime/layers/function/bootstrap
+++ b/runtime/layers/function/bootstrap
@@ -1,35 +1,11 @@
-#!/opt/bin/php
-<?php declare(strict_types=1);
+#!/bin/sh
 
-use Bref\Runtime\LambdaRuntime;
+# Fail on error
+set -e
 
-ini_set('display_errors', '1');
-error_reporting(E_ALL);
-
-$appRoot = getenv('LAMBDA_TASK_ROOT');
-
-/** @noinspection PhpIncludeInspection */
-require $appRoot . '/vendor/autoload.php';
-
-$lambdaRuntime = LambdaRuntime::fromEnvironmentVariable();
-
-$handlerFile = $appRoot . '/' . getenv('_HANDLER');
-if (! is_file($handlerFile)) {
-    $lambdaRuntime->failInitialization("Handler `$handlerFile` doesn't exist");
-}
-
-/** @noinspection PhpIncludeInspection */
-$handler = require $handlerFile;
-
-if (! $handler) {
-    $lambdaRuntime->failInitialization("Handler `$handlerFile` must return a function or Handler object");
-}
-
-$loopMax = getenv('BREF_LOOP_MAX') ?: 1;
-$loops = 0;
-while (true) {
-    if (++$loops > $loopMax) {
-        exit(0);
-    }
-    $lambdaRuntime->processNextEvent($handler);
-}
+while true
+do
+    # We redirect stderr to stdout so that everything
+    # written on the output ends up in Cloudwatch automatically
+    /opt/bin/php "/opt/bref/bootstrap.php" 2>&1
+done
